name: SkUniversal
version: '2.12'
author: Donut
main: us.donut.skuniversal.SkUniversal
api-version: 1.13
depend: [Skript]
softdepend: [AdvancedBan, AdvancedSurvivalGames, Autorank, Bedwars, Bitcoin, Cannons, ClearLag, CombatLog, GriefPrevention, Lockette, LockettePro, LuckPerms, LWC, MinePacks, Parties, PlayerPoints, PlotSquared, PrisonMines, PvPLevels, Shopkeepers, ShopChest, SkyWars, Slimefun]
commands:
  skuniversal:
    description: The main SkUniversal command
    usage: /skuniversal
    permission: skuniversal.info
permissions:
  skuniversal.info:
    description: Allows the use of /skuniversal
    default: op